from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REMOVE = (
    "docs/.capacity_e2e_scope_locked",
    "docs/PM_CAPACITY_E2E_BRANCH_NOTE.md",
    "docs/PM_CAPACITY_E2E_CHECKPOINT.md",
    "docs/PM_CAPACITY_E2E_DO_NOT_MERGE",
    "docs/PM_CAPACITY_E2E_EXECUTION_NOTE.md",
    "docs/PM_CAPACITY_E2E_FINAL_PREMERGE.md",
    "docs/PM_CAPACITY_E2E_PR_GATE.md",
    "docs/PM_CAPACITY_E2E_PR_READY.md",
)

STATUS = """# Capacity E2E PM Status

- Runtime integration: VERIFIED
- Economic integrity: VERIFIED
- Risk fail-closed boundary: VERIFIED
- Scenario → Valuation → PER → Audit capacity path: VERIFIED
- Capacity Audit → Intrinsic Freeze binding certificate: VERIFIED
- Deterministic report form: VERIFIED
- Actual 33-stage LIVE_PRIMARY fixture report: VERIFIED
- Full regression: VERIFIED before finalization commit
- OCI regression: VERIFIED before finalization commit
- Merge: gated on final-head PR checks and post-merge main validation
"""

VALIDATION = """# Capacity Commitment LIVE_PRIMARY Validation

This change closes the execution-control defect exposed by the Sanil Electric analytical-equivalent run.

## Proven contracts

1. `capacity_manufacturing` executes a typed Capacity Commitment Gate before the LLM Bridge Analyst.
2. Missing commitment or bridge-consumption providers fail closed instead of falling back to analyst priors.
3. Every Core-required project must consume capacity, CAPEX and ramp Bridges before Scenario compilation.
4. Scenario, deterministic valuation and Warranted PER preserve the same project-scoped economic paths.
5. Core capacity Evidence cannot be reused to open Expansion PER.
6. Capacity omission, baseline inclusion, cancellation and double-count checks run before generic Audit.
7. A Capacity Freeze binding certificate combines the Capacity Audit identity and immutable Intrinsic Freeze token before Street data is loaded.
8. A report is labelled `VERIFIED_FROZEN` only with a complete 33-stage trace, Freeze token and all applicable Evidence, Capacity, Beta, WACC, Scenario, Valuation and Audit identities.

## Validation commands

```bash
PYTHONPATH=src python scripts/render_verified_report_form.py
pytest -q
valuation-engine examples/oci/company.yaml
```

The committed `PRISM_ACTUAL_RUNTIME_REPORT.md` is generated by a successful canonical 33-stage deterministic LIVE_PRIMARY fixture. It proves orchestration/report execution, not current live Sanil Electric source coverage or a Sanil fair value.
"""


def main() -> int:
    for relative in REMOVE:
        path = ROOT / relative
        if path.exists():
            path.unlink()
    (ROOT / "docs" / "PM_CAPACITY_E2E_STATUS.md").write_text(
        STATUS, encoding="utf-8"
    )
    (ROOT / "docs" / "PM_CAPACITY_E2E_VALIDATION.md").write_text(
        VALIDATION, encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
