from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PORTFOLIO = REPO_ROOT / "ops" / "project_portfolio.yaml"
DEFAULT_OUTPUT = REPO_ROOT / "PROJECT_STATUS.md"
READINESS_PATH = REPO_ROOT / "config" / "live_primary_readiness.yaml"
METHOD_CAPABILITY_PATH = REPO_ROOT / "config" / "valuation_method_capability_registry.yaml"


def _load_yaml(path: Path) -> dict:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} root must be a mapping")
    return payload


def _verified_points(department: dict) -> int:
    points = int(department.get("baseline_accepted_points", 0))
    for milestone in department.get("accepted_milestones", ()) or ():
        if milestone.get("status") == "VERIFIED":
            if not milestone.get("accepted_sha") or not milestone.get("validation_evidence"):
                raise ValueError(f"VERIFIED milestone {milestone.get('id')} requires accepted_sha and validation_evidence")
            points += int(milestone.get("points", 0))
    return points


def _pct(accepted: int, design: int) -> int:
    if design <= 0:
        raise ValueError("department design_points must be positive")
    if accepted < 0 or accepted > design:
        raise ValueError(f"accepted points {accepted} exceed design points {design}")
    return int(round(accepted * 100 / design))


def _readiness_metrics() -> dict[str, int]:
    readiness = _load_yaml(READINESS_PATH)
    stages = readiness.get("stages")
    if not isinstance(stages, dict) or not stages:
        raise ValueError("live_primary_readiness.yaml has no stages")
    counts = Counter(str(row.get("status")) for row in stages.values())
    ready = counts["LIVE_READY"] + counts["RUNTIME_READY"]
    gaps = counts["ADAPTER_REQUIRED"] + counts["SHADOW_ONLY"] + counts["CONDITIONAL_NOT_IMPLEMENTED"]
    return {"mapped": len(stages), "ready": ready, "partial": counts["PARTIAL_LIVE"], "gaps": gaps}


def _method_metrics() -> dict[str, int]:
    registry = _load_yaml(METHOD_CAPABILITY_PATH)
    families = registry.get("execution_families") or {}
    bindings = registry.get("bindings") or {}
    total = executable = explicit_gaps = 0
    for methods in bindings.values():
        for binding in methods.values():
            total += 1
            status = families.get(binding.get("execution_family"), {}).get("runtime_status")
            if status == "NOT_IMPLEMENTED":
                explicit_gaps += 1
            else:
                executable += 1
    return {"total": total, "executable": executable, "gaps": explicit_gaps}


def _mermaid_label(value: object) -> str:
    return str(value).replace('"', "'").replace("\n", " ")


def _ids_for_statuses(work_items: list[dict], statuses: set[str]) -> str:
    ids = [f"`{item['id']}`" for item in work_items if str(item.get("status")) in statuses]
    return ", ".join(ids) or "—"


def render(portfolio: dict) -> str:
    departments = portfolio.get("departments") or []
    work_items = portfolio.get("work_items") or []
    handoffs = portfolio.get("accepted_handoffs") or []
    if not departments:
        raise ValueError("project portfolio requires departments")

    total_design = sum(int(dep["design_points"]) for dep in departments)
    department_rows = []
    total_accepted = 0
    for dep in departments:
        accepted = _verified_points(dep)
        design = int(dep["design_points"])
        total_accepted += accepted
        department_rows.append((dep, accepted, design, _pct(accepted, design)))

    delivery = Counter(str(item.get("status")) for item in work_items)
    readiness = _readiness_metrics()
    methods = _method_metrics()
    overall_pct = _pct(total_accepted, total_design)

    lines: list[str] = []
    lines += ["# PRISM Project Status", "", "> Generated from `ops/project_portfolio.yaml`; do not edit this file directly.", ""]
    lines.append(f"- Blueprint: **{portfolio.get('blueprint', 'unspecified')}**")
    lines.append(f"- Design progress: **{overall_pct}% ({total_accepted}/{total_design} accepted milestone points)**")
    lines.append(
        "- Current delivery: **"
        f"{delivery['ACTIVE']} ACTIVE / {delivery['READY']} READY / {delivery['BLOCKED']} BLOCKED / "
        f"{delivery['BACKLOG']} BACKLOG / {delivery['MERGED_PENDING_ACCEPTANCE']} MERGED PENDING ACCEPTANCE**"
    )
    baseline = portfolio.get("validation_baseline") or {}
    if baseline.get("accepted_sha"):
        lines.append(f"- Accepted validation baseline: `{baseline['accepted_sha']}`")
    lines.append(f"- Updated: **{portfolio.get('updated', 'unknown')}**")
    lines += ["", "Progress is conservative: ACTIVE/READY/BLOCKED/BACKLOG/MERGED_PENDING_ACCEPTANCE work receives zero credit until every required acceptance check is VERIFIED or explicitly ADR-waived."]
    if portfolio.get("recovery_note"):
        lines += ["", f"> Recovery note: {portfolio['recovery_note']}"]

    lines += ["", "## Execution horizon", ""]
    lines.append(f"- Now: {_ids_for_statuses(work_items, {'ACTIVE'})}")
    lines.append(f"- Next: {_ids_for_statuses(work_items, {'READY'})}")
    lines.append(f"- Later: {_ids_for_statuses(work_items, {'BLOCKED', 'BACKLOG'})}")
    lines.append(f"- Pending acceptance: {_ids_for_statuses(work_items, {'MERGED_PENDING_ACCEPTANCE'})}")

    lines += ["", "## Organization", "", "```mermaid", "flowchart TB"]
    lines.append(f'  PM["PM / Integrator<br/>Design {overall_pct}% ({total_accepted}/{total_design})<br/>Now: {delivery["ACTIVE"]} ACTIVE workstreams coordinated"]')
    node_names = ["PMO", "EVIDENCE", "RUNTIME", "VALUATION", "CALIBRATION", "POST_FREEZE", "PLATFORM", "QA_RELEASE"]
    for node, (dep, accepted, design, pct) in zip(node_names, department_rows):
        lines.append(f'  PM --> {node}["{_mermaid_label(dep["name"])}<br/>Design {pct}% ({accepted}/{design})<br/>Now: {_mermaid_label(dep.get("current_work", "—"))}"]')
    lines.append("```")

    lines += ["", "## Department status", "", "| Department | Design progress | Current work |", "|---|---:|---|"]
    for dep, accepted, design, pct in department_rows:
        lines.append(f"| {dep['name']} (`{dep['id']}`) | **{pct}% ({accepted}/{design})** | {dep.get('current_work', '—')} |")

    lines += ["", "## Current execution queue", "", "| Priority | Status | Work item | Owner | Current step | Dependencies |", "|---|---|---|---|---|---|"]
    priority_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    status_order = {"ACTIVE": 0, "MERGED_PENDING_ACCEPTANCE": 1, "READY": 2, "BLOCKED": 3, "BACKLOG": 4}
    for item in sorted(work_items, key=lambda row: (priority_order.get(str(row.get("priority")), 9), status_order.get(str(row.get("status")), 9), str(row.get("id")))):
        deps = ", ".join(f"`{dep}`" for dep in (item.get("dependencies") or [])) or "—"
        lines.append(f"| {item.get('priority', '—')} | **{item.get('status', '—')}** | `{item['id']}` — {item['title']} | `{item['owner']}` | {item.get('current_step', '—')} | {deps} |")

    lines += ["", "## Objective readiness (derived, not manually scored)", ""]
    lines.append(f"- Canonical stages mapped: **{readiness['mapped']}/{readiness['mapped']}**")
    lines.append(f"- `LIVE_READY` or `RUNTIME_READY`: **{readiness['ready']}/{readiness['mapped']}**")
    lines.append(f"- `PARTIAL_LIVE`: **{readiness['partial']}/{readiness['mapped']}**")
    lines.append(f"- Explicit runtime gaps: **{readiness['gaps']}**")
    lines.append(f"- Executable method bindings: **{methods['executable']}/{methods['total']}** ({methods['gaps']} explicit `NOT_IMPLEMENTED`)")
    lines += ["", "These registry metrics measure typed runtime readiness, not full live source/provider coverage. The design-progress score above includes product, acceptance, source and release gaps."]

    lines += ["", "## Accepted handoffs", "", "| Handoff | To | Head | Validation evidence | Closes | Residual work |", "|---|---|---|---|---|---|"]
    for item in handoffs:
        evidence = ", ".join(f"`{value}`" for value in (item.get("validation_evidence") or [])) or "—"
        closes = ", ".join(f"`{value}`" for value in (item.get("closes") or [])) or "—"
        residual = ", ".join(f"`{value}`" for value in (item.get("residual_work") or [])) or "—"
        lines.append(f"| `{item['id']}` | `{item['to']}` | `{item['head']}` | {evidence} | {closes} | {residual} |")

    lines += ["", "## Update contract", "", "1. Change delivery state only in `ops/project_portfolio.yaml`.", "2. Keep one ACTIVE work item per owner and no overlapping ACTIVE write scopes.", "3. Link implementation PRs with `github_pr`; merged PRs remain `MERGED_PENDING_ACCEPTANCE` until PM acceptance.", "4. Record acceptance as VERIFIED only with exact-SHA validation evidence; use an ADR for any waiver.", "5. Add the complete handoff before REVIEW/DONE; only the PM/Integrator closes a milestone.", "6. Validate with `PYTHONPATH=src python scripts/validate_project_portfolio.py`, regenerate with `render_project_status.py --write`, then verify with `--check`.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render or verify PRISM PM project status")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--portfolio", type=Path, default=DEFAULT_PORTFOLIO)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rendered = render(_load_yaml(args.portfolio))
    if args.write:
        args.output.write_text(rendered, encoding="utf-8")
        print(f"wrote {args.output}")
        return 0
    if not args.output.exists():
        print(f"missing generated status file: {args.output}")
        return 1
    if args.output.read_text(encoding="utf-8") != rendered:
        print("PROJECT_STATUS.md is stale; run PYTHONPATH=src python scripts/render_project_status.py --write")
        return 1
    print("PROJECT_STATUS.md is synchronized")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
